name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-11, windows-latest]
        os: [ubuntu-latest, macos-11]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies (Mac)
        run: |
            brew install freeimage
            rm /usr/local/opt/freeimage/lib/libfreeimage.dylib
        if: matrix.os == 'macos-11'

      - name: Update packages (Linux)
        run: sudo apt update
        if: matrix.os == 'ubuntu-latest'
      - name: Install Dependencies (Linux)
        run: sudo apt install libfreeimage-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Make (Linux)
        run: make CFLAGS="-Wall"
        if: matrix.os == 'ubuntu-latest'

      - name: Make (Mac)
        run: make
        if: matrix.os == 'macos-11'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: build
